### ISSUE TITLE
MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by gaurav341** [evanshortiss/fh-service-request#1]
I have used your plugin on RHMAP and the got teh following error

Internal error: { [Error: Cannot find module '/home/fh/apps/dhfl-js3xg2455hzthufd7ebviqe5-dev/src/fhconfig.json'] code: 'MODULE_NOT_FOUND' }

**Comment by evanshortiss** [comment]
@gaurav341 ah, interesting. This is something that should be easy to fix, but I won't get a chance until a little later today. As a workaround can you create an _fhconfig.json_ in the root of your app (same folder as _application.js_) and copy the sample JSON [here](https://github.com/evanshortiss/fh-service-request#local-development)? This should unblock you.

Thanks for reporting it.

**Comment by gaurav341** [comment]
Thanks its working now.
